### ISSUE TITLE
[1.21-Neo] Crash when trying to craft with items through connected chests.

### ISSUE THREAD

**Issue by Gbergz** [Tfarcenim/crafting-station#100]
**Info**
When trying to craft something in the Crafting Station and you pull items from connected chests when using EMI/JEI transfer game crashes.

The specific chests were Gold & Diamond chest from Expanded Storage.

**Versions**
NeoForge: 21.0.97
CraftingStation: 1.21-1
Expanded Storage: 14.0.5

**Crash-report:** 
https://gist.githubusercontent.com/Gbergz/290cb3a39bec172cf74fa66e70199f70/raw/c75ff50845bd94cfead56ea92a9a1248ad5f1af6/gistfile1.txt

**Comment by Tfarcenim** [comment]
I have checked this against Metal Barrels which is fine, does this crash only occur with Expanded storage, crafting station, and jei?

**Comment by Gbergz** [comment]
Haven't checked but it does happen only with those chests pretty sure, couldn't reproduce it with vanilla chests.

**Comment by Gbergz** [comment]
Placing a Gold Chest on one side then a Diamond chest on the other, then placing same materials in both chests, having excess materials over then pulling them out of the table crashes the game.

New crash report: https://gist.githubusercontent.com/Gbergz/8ed274df5d5eb33c3597629cfac6da32/raw/aa66697fb90a99722d913e29a15f17f1d1e897a1/gistfile1.txt (looks the same)

**Comment by Gbergz** [comment]
I think it's an issue with Crafting Station, Expanded Storage & MouseTweaks.

Reproduced it with just these mods:
expandedstorage-14.0.5+1.21-neoforge.jar
jei-1.21-neoforge-19.5.2.66.jar
MouseTweaks-neoforge-mc1.21-2.26.jar
craftingstation-neoforge-1.21-1.jar

**Comment by Tfarcenim** [comment]
Found the issue, fixed in 1.21-2

**Comment by Gbergz** [comment]
Awesome. thanks!
