### ISSUE TITLE
[1.12.2] Placing Silent's Gems Machete & Paxel on the bottom rows causes a crash

### ISSUE THREAD

**Issue by shipfridge** [Tfarcenim/crafting-station#102]
https://mclo.gs/xtHxZo6
https://mclo.gs/BP3CWku
https://mclo.gs/Bxqg7Ka

Placing said item(s) on the top and middle rows work just fine

**Comment by Tfarcenim** [comment]
at net.silentchaos512.gems.recipe.RecipeDecorateTool.func_77572_b(RecipeDecorateTool.java:58)
13

Silent's gems is asking for a slot that doesn't exist without bothering to check if it exists or not.  Not an issue on Crafting Station's end.
