### ISSUE TITLE
Mod doesn't work with Crafting Tweaks

### ISSUE THREAD

**Issue by BigAl607** [Tfarcenim/crafting-station#15]
There is no option for Crafting Tweaks when the two mods are installed (see picture). Shift-crafting also doesn't work

Minecraft version 1.12.2
Forge 14.23.5.2844
Custom modpack

![2019-09-01_18 29 09](https://user-images.githubusercontent.com/13182567/64083016-7f316a00-cce6-11e9-97b2-eb5ea386a6b3.png)

**Comment by Tfarcenim** [comment]
resolved in 0.1.3

**Comment by WenXin20** [comment]
Could compat be added for 1.14.4 as well?
