### ISSUE TITLE
JEI doesn't detect the side inventory.

### ISSUE THREAD

**Issue by WenXin20** [Tfarcenim/crafting-station#16]
Minecraft v1.12.2
Forge v14.23.5.2838
Crafting Station v0.1.3
JEI v4.15.0.289

The side inventory is not being detected by JEI's favorite bar on the left, which overlaps the side inventory. 
This means if someone has a lot of favorited items, it will overlap the items in the side inventory.
If cheat mode is enabled with JEI, items that the player tries to place in the side inventory will instead be deleted by JEI.

**Comment by WenXin20** [comment]
This also affects 1.14.4

**Comment by Tfarcenim** [comment]
Fixed in 0.1.6

**Comment by Tfarcenim** [comment]
partily fixed in 2.0.3, but jei is still doing some weirdness, see also https://github.com/mezz/JustEnoughItems/issues/1730

**Comment by WenXin20** [comment]
I think this is fixed and can be closed, correct?

**Comment by Tfarcenim** [comment]
yeah, both versions were fixed on my end

**Comment by WenXin20** [comment]
In `v2.1.3b` of `Minecraft v1.14.4`, I noticed that the side inventory is still overlapped slightly.

![2019-11-29_18 59 52](https://user-images.githubusercontent.com/12000593/70176434-17503e00-169e-11ea-80af-346db7ff39cd.png)

**Comment by Tfarcenim** [comment]
fixed, but not worth for a tiny change
