### ISSUE TITLE
Shift-click no longer works

### ISSUE THREAD

**Issue by choekstr** [Tfarcenim/crafting-station#17]
Shift-Clicking of items from players inventory into the crafting table is broken in the 0.1.3 version.

Shift-Clicking of items in the crafting station should send to connected chest if there is already a partial stack (previous behavior and Tinker's construct behavior and Applied Energistic 2 behavior and Refined Storage behavior).

**Comment by WenXin20** [comment]
Shift-click crafting is also weird in 1.14.4

It will attempt to go into the side inventory, but if it's even only halfway full, shift-click crafting doesn't work at all.
