### ISSUE TITLE
0.1.4 issues

### ISSUE THREAD

**Issue by choekstr** [Tfarcenim/crafting-station#18]
Using 0.1.4:
Shift click of item while in inventory has it to go to connected chest instead of crafting station.  Should instead be going into the crafting station.

Shift click in crafting station doesn't do anything anymore.  just stopped working.  Should stack with inventory in connected chest if possible, if not should return to player inventory.

Additional items I noticed
**in Mod List the mod shows:**
Crafting Station
@VERSION@
0 child mods

**Description in Mod List:**
Crafting Station
Version: @VERSION@
Mod State: Available

**Comment by Tfarcenim** [comment]
> Shift click of item while in inventory has it to go to connected chest instead of crafting station
that's kind of intended since vanilla table doesn't support shift click

> Shift click in crafting station doesn't do anything anymore. just stopped working. Should stack with inventory in connected chest if possible, if not should return to player inventory.

this one's a problem, if I have it going to the container, people will complain that it doesn't go to the player, if I have it go to the player people will complain that it doesn't go to the inventory

**Comment by choekstr** [comment]
why are you changing what Tinker's does?  It was this way up until your rewrite on 1.0 where YOU changed it before anyone mentioned it.  Mostly likely an oversight during the rewrite.  No one is complaining of the way Tinker's station works but effectively you have a vanilla crafting station now with no ability to interact from a connected chest, just see it.  

The whole concept of why I requested this of critflaw who reached out to you is to have JUST the crafting station from Tinker's but not the rest of the mod.  Now it is just a vanilla crafting table with a view of an inventory next to it.

**Comment by Tfarcenim** [comment]
I forgot about it when doing the rewrite just getting it to a usable state without 90% dead code, now that it finally stopped crashing I can work on the finer details.

**Comment by choekstr** [comment]
yeah, completely agree with the whole rewrite, kudos on doing that btw!  That is a large undertaking but I agree probably 90% dead code that doesn't apply is an accurate guess.  

Just go back and look at 0.0.4 version, which is what I use since it works perfectly.  Or you can of course look at tinker's and see what the behavior is like.

Here are my quick notes:
- Connected chest support.  This should pull any items needed from the chest or inventory.  
- Ideally you can find a way to make the connected chest view larger than the default because things like crates you have to scroll forever and higher gui sizes there is a lot of wasted space
- Shift-click an item from inventory will always go into crafting station.  
- Shift-click an item in crafting station will try first to fill a stack in the connected chest.  if no stack or stack exists but is full then push the item to player inventory.
- mouse tweaks roller mousewheel inserts/pulls directly to crafting station.  this, iirc, also honors the partial stack pattern and puts back in connected chest but in players inventory if full.
- crafting tweaks support has never put items back into connected chest but it would be ideal if it followed the same rule of partial stacks as well.  My guess is the Tinker's team were never able to get it to behave since it's a crafting tweaks issue, not a tinkers crafting station issue.

**Comment by Tfarcenim** [comment]
I think I've got everything now

**Comment by choekstr** [comment]
Just wanted to confirm all is good and 0.1.5 seems to work exactly like it should from what I have tested.  great job!
