### ISSUE TITLE
Ghost diamonds in crafting grid

### ISSUE THREAD

**Issue by al132mc** [Tfarcenim/crafting-station#2]
**Issue description:**
Only on servers, after the server has been up for a little while all players will start seeing ghost crafting recipes for 64 diamonds when their grid is empty in crafting stations. **This bug does not happen with vanilla crafting tables.** They can grab the diamonds, but then when they resync their inventory with something like inventory tweaks sorting or re-login, or whatever, the diamonds will dissapear. Please let me know if you need more information.

![image](https://user-images.githubusercontent.com/39097092/59552902-771d2600-8f52-11e9-912f-69a6092dde10.png)

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.5.2838
* Mantle: Not installed
* Tinkers Construct: Not installed
* This mod: 0.0.4

**Comment by Tfarcenim** [comment]
wonder if it's still an issue in 0.1.0

**Comment by al132mc** [comment]
Unsure, I updated and immediately a user was reporting a crash whenever they crafted something, so I have to downgrade for now. [log](https://pastebin.com/y8VTkeKj)

**Comment by Tfarcenim** [comment]
yeah, try 0.1.3 and see if that works

**Comment by al132mc** [comment]
Sorry, just getting around to this now. I will hopefully know within a day or two...

**Comment by Tfarcenim** [comment]
gonna close in a week from now if I don't hear anything
