### ISSUE TITLE
Suggestion: A half-block (slab) version of the Crafting Station that could be placed on top of other half-blocks (slabs)

### ISSUE THREAD

**Issue by SepSol** [Tfarcenim/crafting-station#25]
![image](https://user-images.githubusercontent.com/47871887/67165416-6a419080-f391-11e9-8065-04b365d5e6db.png)
![image](https://user-images.githubusercontent.com/47871887/67165418-71689e80-f391-11e9-8894-2d3b914cd192.png)

**Comment by Tfarcenim** [comment]
A slab crafting station is possible, but not inside of another block due to the limitations of mc.

**Comment by SepSol** [comment]
What do you mean by it being inside another block? 🤔

**Comment by Tfarcenim** [comment]
I mean where you can't put 2 different slabs inside of the same block space

**Comment by SepSol** [comment]
Oh, I see. Even if that's the case still the slabbed version of Crafting Station could be useful :)

**Comment by SepSol** [comment]
I'm really trying hard to not create another issue for other wood type versions :D
Have a look at this (by [I Like Wood](https://www.curseforge.com/minecraft/mc-mods/i-like-wood) mod):

![image](https://user-images.githubusercontent.com/47871887/67165694-2ea8c580-f395-11e9-847f-feda0bf51a5f.png)

**Comment by Tfarcenim** [comment]
That would be up to iLikeWood to add, I don't like the idea of 20 new crafting stations that can only be made with a specific wood.

**Comment by SepSol** [comment]
ok, that's fair

**Comment by SepSol** [comment]
This feature was added in latest version. Thanks a lot!
