### ISSUE TITLE
Bug: the items on the crafting table don't change their direction

### ISSUE THREAD

**Issue by SepSol** [Tfarcenim/crafting-station#26]
The recipes are shown correctly and item placement on the table is according the where the player was standing at the time of putting the table down (in this case the red carpet). But the items on the crafting table don't seem to change their direction at all, it would be great if they changed their direction with the table as well.

![image](https://user-images.githubusercontent.com/47871887/67181931-ce447300-f3ea-11e9-88eb-62fdf56272b8.png)

Also could you make the sticks and tools a little bit more noticeable on the table? The planks and logs and full blocks are too big and the sticks are too narrow and small. Can you make them pop more? Like giving them more height(?!). Or maybe lightening the table's top texture a little bit so that their wood texture becomes a little bit more saturated?

**Comment by SepSol** [comment]
Even making the borders of 3x3 grid might work 🤔

**Comment by Tfarcenim** [comment]
items now change their direction as well as of 2.0.8
