### ISSUE TITLE
Slab names don't show well in HWYLA

### ISSUE THREAD

**Issue by SepSol** [Tfarcenim/crafting-station#29]
![image](https://user-images.githubusercontent.com/47871887/68007227-2d7a7100-fc90-11e9-94da-2d58bf6d4b3c.png)

- Minecraft 1.14.4
- Forge 28.1.76
- OptiFine HD U F4
- Hwyla-forge-1.10.6-B67_1.14.4
- craftingstation-2.1.0

**Comment by WenXin20** [comment]
The localization seems to be missing. The item itself also doesn't display correctly.

**Comment by SepSol** [comment]
Thanks, it is now fixed as of 2.1.1 update :)
