### ISSUE TITLE
Bottom of the crafting station is missing texture

### ISSUE THREAD

**Issue by rainbowlack** [Tfarcenim/crafting-station#3]
**Issue description:**
Bottom of the crafting station is missing texture

![missingtexture](https://user-images.githubusercontent.com/52368243/60393003-7e544000-9acb-11e9-8aa3-e8426eb82acc.PNG)

* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.5.2838
* Mantle: Not installed
* Tinkers Construct: Not installed
* This mod: 0.0.4

**Comment by Tfarcenim** [comment]
resolved in 0.1.0
