### ISSUE TITLE
Bug: items on a crafting station (block/slab) are flipped

### ISSUE THREAD

**Issue by SepSol** [Tfarcenim/crafting-station#30]
The directions seem to be ok but the items are flipped on the Crafting Station (on both the full-block version and the half-block version). Below are some screenshots explaining the issue:

![image](https://user-images.githubusercontent.com/47871887/68008141-2143e300-fc93-11e9-8171-ddd0fc422267.png)
![image](https://user-images.githubusercontent.com/47871887/68008153-2739c400-fc93-11e9-8134-af0bebc06cb8.png)

I crafted the top picture in all 4 directions and the results in each one of them is in the second pic.

**Comment by SepSol** [comment]
Thanks for the 2.1.1 update, but the issue exists to some level. Here's what I'm putting on the Crafting Station:

![image](https://user-images.githubusercontent.com/47871887/68113081-265d9800-ff08-11e9-80b3-62ca35f28ea1.png)

And here's what it looks like in all different directions (top is north):

![image](https://user-images.githubusercontent.com/47871887/68113186-64f35280-ff08-11e9-9382-df29e86d6b44.png)

Just turn your head and you'll notice the feather and sword are not facing the right way. This also applies to fishing rods.

**Comment by SepSol** [comment]
Have you noticed my last feedback? 🤔

**Comment by Tfarcenim** [comment]
yes, I have, but no matter what I do, it always seems to end up wrong

**Comment by SepSol** [comment]
Oh, ok. It's better than before though, so no worries!

**Comment by Tfarcenim** [comment]
seems to be fixed now
