### ISSUE TITLE
Cant Access Vanilla GUI

### ISSUE THREAD

**Issue by pandory-network** [Tfarcenim/crafting-station#31]
After Installing the latest Version. I cant Access any Vanilla Crafting Table, Furnace or other Workstation with GUI.

Log show now Errors relatet to craftingstation

**Comment by Tfarcenim** [comment]
any of said log files?

**Comment by Tfarcenim** [comment]
also needed is mod version (latest doesn't cut it), mc version, and modlist (perferably with minimal mods needed to reproduce)

**Comment by pandory-network** [comment]
Sorry I took your time.
I have the mod again installed on my server. Now everything works without problems. I can not reproduce the mistake anymore.

I'll close this problem then.
