### ISSUE TITLE
1st slot in connected inventory isn't seen by crafting station 

### ISSUE THREAD

**Issue by choekstr** [Tfarcenim/crafting-station#32]
Whatever item is in the 1st item in the connected chest/inventory won't be seen by JEI recipes when using crafting station.  Here is a for instance:
- Put a piece of quartz in the first slot (top left if you are looking in the chest or in the crafting station on the attached inventory.
- Put your stone and redstone in slots 2 and 3
- Try to craft a redstone comparator 

Here is an image of what it shows.  The item missing is in the first slot.  If I move it out of the first slot it finds it perfectly:
![ScreenShot 19 11 02-03 03 PM](https://user-images.githubusercontent.com/161085/68076430-47947c00-fd82-11e9-94a7-c09f904e2b21.PNG)

**Comment by Tfarcenim** [comment]
mc version and mod version please

**Comment by choekstr** [comment]
MC 1.12.2
Crafting station: ???  <- Still haven't fixed your version in game :)
![ScreenShot 19 11 02-03 07 PM](https://user-images.githubusercontent.com/161085/68076450-7e6a9200-fd82-11e9-9c5e-f25b49bc6be7.PNG)

**Comment by choekstr** [comment]
It's latest twitch sees, 0.1.6 and it seems like curseforge latest for 1.12.2

**Comment by Tfarcenim** [comment]
fixed in 0.1.7
