### ISSUE TITLE
1.14.4 crashes client.

### ISSUE THREAD

**Issue by Wissi** [Tfarcenim/crafting-station#33]
Place any amount of blocks in crafting station, then right clicking on it to removes 1/2 of it and crashes.
Tried on vanilla crafting table and no issue, no crashing. 
 
Full crash log [here](https://gist.github.com/Wissi/08b2f734c592040fa7d579eff292c28f).

Using: Forge 28.1.79
craftingstation-2.1.1.jar

Reported to Mouse tweaks as well, although it only crashes using your mods crafting table and not vanilla crafting table nor other mods crafting tables.   Link to the report [here](https://github.com/YaLTeR/MouseTweaks/issues/28#issue-516881874).

Hope it helps to get debugged. Thanks.

**Comment by Tfarcenim** [comment]
The bug is in corails pillar, not my mod, report to them

**Comment by Wissi** [comment]
Thanks for the suggestion. 
I have reported to them as you suggest.

It only seems to happen on your crafting table when using Mouse tweaks.

report for Corail is [here](https://github.com/Corail31/corail-pillar/issues/26#issue-516925257).

**Comment by Tfarcenim** [comment]
Hmm, not my fault other people write unsafe recipes.
