### ISSUE TITLE
Crafting station shows connected chest as personal inventory when connected to a double chest

### ISSUE THREAD

**Issue by choekstr** [Tfarcenim/crafting-station#34]
Crafting Station v0.1.7
MC 1.12.2
Forge 14.23.5.2838

For some reason the crafting station is showing the bottom half of a double chest as MY inventory and the top half as the connected chest.  

**Here's my actual inventory:**
![ScreenShot 19 11 09-09 31 PM](https://user-images.githubusercontent.com/161085/68538386-ef88e700-0338-11ea-86bb-642cb94346d2.PNG)

**When I enter the crafting station this is what I see:**
![ScreenShot 19 11 09-09 31 PM 001](https://user-images.githubusercontent.com/161085/68538390-0af3f200-0339-11ea-8472-1f1c2ad66fdf.PNG)

**And here is the connected double chest.  As you can see the bottom half becomes MY inventory when viewing the crafting station:**
![ScreenShot 19 11 09-09 32 PM](https://user-images.githubusercontent.com/161085/68538392-12b39680-0339-11ea-9186-16b10da1fd2d.PNG)

**Comment by choekstr** [comment]
This has never happened to me before with 1.7 but I haven't played with the newest version that much.  I was just using it with Chemical Exchange 1.12 pack and didn't notice anything odd but was using a projectE alchemical chest instead of a double chest so it might just be the pack I am playing now which is Arcane Anarchy.

**Comment by choekstr** [comment]
One more bit of info: I am getting the "An Unknown problem occurred!  Press Ctrl + I for more info" on the top right 5 times.  Here is the paste of the error log for the micro crash: 
https://paste.dimdev.org/gepagahuqu.mccrash

**Comment by Tfarcenim** [comment]
![image](https://user-images.githubusercontent.com/44327798/68538557-7a231380-0344-11ea-8a4b-5c8f6103b3db.png)

Can't seem to reproduce on my end, this is with only crafting station and jei, perhaps mod interference?

**Comment by choekstr** [comment]
ok, was just able to replicate it elsewhere.  try putting down a single vanilla chest, fill it with some things, then add another vanilla chest to make it a double chest, add items again (these will be at the top and the original stuff will be the middle down.  then it happens.

**Comment by Tfarcenim** [comment]
Alright, bug confirmed, vanilla chests are stupid will see what I can do about it

**Comment by Tfarcenim** [comment]
Alright hotfix out, let me know if that fixes it.

**Comment by choekstr** [comment]
trying it out now

**Comment by choekstr** [comment]
**Hmm, still the same issue on 0.1.7a**
![ScreenShot 19 11 09-11 28 PM](https://user-images.githubusercontent.com/161085/68539394-a771c080-0348-11ea-9ed7-fb32f70f133e.PNG)

**Spammed with errors and all my inventory is replaced**
![ScreenShot 19 11 09-11 29 PM](https://user-images.githubusercontent.com/161085/68539404-ccfeca00-0348-11ea-857a-9ed92c5913d8.PNG)

**Actual inventory:**
![ScreenShot 19 11 09-11 30 PM](https://user-images.githubusercontent.com/161085/68539422-0df6de80-0349-11ea-9da8-ffc40a4351b0.PNG)

**Comment by Tfarcenim** [comment]
annoying, thought I had it

**Comment by choekstr** [comment]
So did I.  I was getting ready to close the issue

**Comment by Tfarcenim** [comment]
Alright, this time I actually fixed it

**Comment by choekstr** [comment]
Yes, confirmed, this seems to have fixed it.  great job as always!
