### ISSUE TITLE
Large Inventories Missing the Scrollbar

### ISSUE THREAD

**Issue by WenXin20** [Tfarcenim/crafting-station#35]
`Minecraft v1.14.4`
`Forge v28.1.87`
[`Metal Barrels v1.4`](https://www.curseforge.com/minecraft/mc-mods/metal-barrels) 
[`Better Crates v1.0.1`](https://www.curseforge.com/minecraft/mc-mods/better-crates) 
`Crafting Station v2.1.1`

 I recently noticed that inventories larger than a double chest doesn't provide a scrollbar in the crafting station anymore. 

 This was tested using a Diamond Better Crate and also the Crystal Barrel from the Metal Barrels mod.

**Comment by Tfarcenim** [comment]
![image](https://user-images.githubusercontent.com/44327798/68738073-5580a300-05b3-11ea-95d9-91c68e65c713.png)
hmm, don't seem to have the issue with the metal barrels stuff, is there anything else next to it?

**Comment by WenXin20** [comment]
Interesting. There was also a double chest next to it, but I'll have to check later once my laptop decides to stop being slow...

Did you try the Diamond Crate from Better Crates? That was also next to it.

**Comment by Tfarcenim** [comment]
give me a second, adding it to test environment

**Comment by Tfarcenim** [comment]
![2019-11-13_01-31-35](https://user-images.githubusercontent.com/44327798/68738851-64685500-05b5-11ea-8398-e022dcf79ece.gif)
seems fine to me

**Comment by WenXin20** [comment]
Hmm, I'll have to check tomorrow.

**Comment by WenXin20** [comment]
Ok, I figured out what's going on.

If I place a chest on one side and place a Crystal Barrel on the other side, then a scrollbar won't appear if the chest is the first tab in the side inventory.

But if the Crystal Barrel is the first tab and the chest is on the second tab, then a scrollbar will appear for both inventories, even though the chest doesn't need it.

P.S. I also noticed a lag spike whenever I first place down a station. It sometimes also lags when placing a chest next to a station that doesn't have a chest next to it.

**Comment by WenXin20** [comment]
I also noticed that with Quark's new Search Bar, which can be opened by clicking on the filter button, will appear in the crafting station if it was clicked on in a chest. But since the Quark buttons don't appear in the station, there's not a way to close the search bar w/o exiting the station. Not sure if that's fixable or not.

**Comment by Tfarcenim** [comment]
so the bug is scrollbars appearing for inventories that aren't large enough to have one.  As for quark stuff that would be up to them to fix.

**Comment by WenXin20** [comment]
Yes, but if the first tab is a chest, but the second tab is the Crystal Barrel, then the Crystal Barrel won't have a scrollbar at all. 

So I think the bug is that the scrollbar only appears if the first tab needs it.

I can send images later if needed.

**Comment by WenXin20** [comment]
Works great now, thank you!
Is it possible for the station to stay on the same tab when exiting and reopening the station?

**Comment by Tfarcenim** [comment]
yes that would be possible

**Comment by Tfarcenim** [comment]
and done

**Comment by WenXin20** [comment]
Thanks for the help!
