### ISSUE TITLE
Cannot extract output

### ISSUE THREAD

**Issue by NillerMedDild** [Tfarcenim/crafting-station#37]
This bug occurs in Enigmatica 4 v0.3.1
- craftingstation-2.1.3a

Placing a recipe in the Crafting Station, closing the Crafting Station and then reopening it, the output of the recipe cannot be extracted.

The logs don't say anything about it, but here's the latest.log anyway
https://gist.github.com/NillerMedDild/89f6f9c4b1e1f348c69d0e9649b935ef

**Comment by Tfarcenim** [comment]
Dedicated server or single player?

**Comment by Tfarcenim** [comment]
and can it be reproduced in a clean instance, (ie only craftingstation + jei)

**Comment by NillerMedDild** [comment]
I knew I forgot something - Single player. I'll setup a clean instance now.

**Comment by NillerMedDild** [comment]
It happens in a clean instance (+JEI) in single player.

**Comment by NillerMedDild** [comment]
Thanks!
