### ISSUE TITLE
OpenGL Stack underflow

### ISSUE THREAD

**Issue by SaltSouls** [Tfarcenim/crafting-station#38]
## Bug Report
**Synopsis of Issue:**
I keep getting this error on screen when I go to use the crafting station. It doesn't crash and it seems to work as intended. Not sure if it is an issue with Optifine, or if there is a bug in the rendering engine. All I know is that this is the only work station that gives me this error.

- Forge Version: 28.1.102

**Image:**
![2019-12-04 (1)](https://user-images.githubusercontent.com/36361103/70187658-a1e76c00-16a3-11ea-9cfd-3128721b17fd.png)

**Comment by Tfarcenim** [comment]
optifine issue, never figured out the cause
