### ISSUE TITLE
Crafting Station can be used to rob Good O'l Currency Vending Machine

### ISSUE THREAD

**Issue by Colt44Magnum** [Tfarcenim/crafting-station#4]
**Issue description:**
Can rob items out of Good O'l Currency Vending machine using crafting bench. The Vending machines are locked to anyone but the owner when everything is how its supposed to be. 
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* Mantle: not installed 
* Tinkers Construct: not installed
* Crafting Station: 0.0.4

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Good O'l Currency Mod v. 1.12.0-1.3.9
Crafting Station v. 0.0.4

![image](https://user-images.githubusercontent.com/51977107/60409208-a9549780-9b90-11e9-8a46-26fbd5ff97f2.png)
Allowed me to bypass the lock, one of the chorus fruit is from the vending machine and the five cent pieces are from the vending machines internal storage

![image](https://user-images.githubusercontent.com/51977107/60409267-e1f47100-9b90-11e9-89c0-48458ee8b516.png)
The vending machines normal interaction when clicked on, notice the blank space with a 1. the chorus fruit no longer is sold because I was able to take it out

**Comment by Tfarcenim** [comment]
oh no, it's blacklist time
