### ISSUE TITLE
[1.12.2] Pyrotech's Campfire cannot be blacklisted

### ISSUE THREAD

**Issue by katubug** [Tfarcenim/crafting-station#40]
I was testing things out in a modpack I'm working on, and discovered that the Crafting Station can access the Campfire's inventory. I attempted to blacklist it in the config by adding `pyrotech_campfire` to the list, but it doesn't seem to have worked.

![2020-01-01_22 16 03](https://user-images.githubusercontent.com/20935286/71651574-534de180-2ce4-11ea-826a-6cab8762e63a.png)
![2020-01-01_22 17 07](https://user-images.githubusercontent.com/20935286/71651620-a9228980-2ce4-11ea-8cc1-fba5f3be4189.png)

These screenshots were taken with the config already saved, and I also attempted breaking and replacing both the campfire and the crafting station. Please let me know if you'd like any other information! :)

Minecraft 1.12.2
Crafting Station 0.1.7b
Pyrotech 1.4.19
Forge 2847

**Comment by Tfarcenim** [comment]
it's "pyrotech:tile.tilecampfire"

**Comment by katubug** [comment]
Ah shoot dang, I should have checked for that. My apologies, thanks for the help!

**Comment by Tfarcenim** [comment]
resolved
