### ISSUE TITLE
Showing 64 diamonds.?

### ISSUE THREAD

**Issue by JepsenDK** [Tfarcenim/crafting-station#48]
I am trying to use CraftTweaker and make som ekstra recepies for my modpack. But when I use your mod is shows the wrong GUI on the output. 
When I try to make a simpel 4 chest recepi it shows 64 diamons as shown on picture.

I am using 1.12.2 and 0.1.7 mod.

![image](https://user-images.githubusercontent.com/36129962/74414665-28f25680-4e42-11ea-99e2-5e6c0177fe08.png)

**Comment by Tfarcenim** [comment]
a mod is adding an invalid recipe, find out which one

**Comment by JepsenDK** [comment]
It works in vanilla table. And it shows that in all recepies I made with CraftTweaker.
It stills give me the right result, it just shows the wrong thing.

I made a 16 sticks with 2 logwood and a hopper with the same result.

It must be something thats shows wrong in the crafting table since it works in all other crafting tables.

**Comment by Tfarcenim** [comment]
so that means it's definitely a mod adding a broken recipe then, all my table does is call the vanilla craft methods.
