### ISSUE TITLE
Incorrectly detects stack size if larger than 64

### ISSUE THREAD

**Issue by Lavan** [Tfarcenim/crafting-station#49]
Minecraft: 1.15.2
Forge: 31.1.18
CraftingStation: 3.0.5
Dank Storage 2.5

When I combine the crafting station with one or more dank storages the crafting station will incorrectly detect the number of items in the storage modules. 0-64 works well but above that the detected size will be stacksize % 64 instead.

**Comment by Tfarcenim** [comment]
The vanilla tic station also does this, I'll find a workaround at some point

**Comment by Tfarcenim** [comment]
Made it a little better, it won't split large stacks anymore but it still won't merge them.
