### ISSUE TITLE
Alignment in JEI Search mode is off slightly

### ISSUE THREAD

**Issue by choekstr** [Tfarcenim/crafting-station#5]
**In JEI "Item search" mode, alignment is slightly off still**

See this image for reference and note the double click in JEI search field to make it yellow then enter the crafting station:
![ScreenShot 19 07 07-09 19 AM](https://user-images.githubusercontent.com/161085/60769761-564f7880-a099-11e9-9bd2-9fc47eb33013.PNG)

**Versions: 0.4
* Minecraft: 1.12.2
* Forge:  forge-14.23.5.2838
* Mantle: NA
* Tinkers Construct: No

**Seems to be unique to crafting station and not happen with Tinkers**

**Comment by Tfarcenim** [comment]
does it still happen with 0.1.0?

**Comment by Tfarcenim** [comment]
btw, that's not jei that's adding the highlight, so it might be a possible mod conflict

**Comment by choekstr** [comment]
Double clicking in jei search puts one into "highlight" mode where only what you search for is normal color and everything else is darkened, thus the highlight which is really more of a lowlight overlay.  Pretty sure it's JEI that is putting that on there whenever you double click in the JEI search bar.

But the good news is that your rewrite and code cleanup seems to have fixed it wonderfully in 0.1.0.  I'll keep testing and let you know if there is anything else I notice.

Great job on the timely fix and also kudo's for migrating over to 1.14!
