### ISSUE TITLE
Blocking access to chests

### ISSUE THREAD

**Issue by Sepera-okeq** [Tfarcenim/crafting-station#50]
Tell me why there is no config to allow or prohibit extracting items from nearby chests?I just want to turn it off,but not clean the workbench. Can you tell?

I have just starts happening the game with the inventory from the chest fashion,I originally wanted to block the function of collecting things from the chests

Minecraft Version: 1.12.2
Forge 14.23.5.2847

**Comment by Tfarcenim** [comment]
there is a config https://github.com/Tfarcenim/crafting-station/blob/master/src/main/java/com/tfar/craftingstation/Configs.java#L20-L22
