### ISSUE TITLE
Crash when trying to access the table...

### ISSUE THREAD

**Issue by RepoDraghon** [Tfarcenim/crafting-station#53]
It was working when I started the world but after a few shutdowns and restarts... this crash happens...
[crash-2020-04-28_18.43.25-server.txt](https://github.com/Tfarcenim/crafting-station/files/4549446/crash-2020-04-28_18.43.25-server.txt)

Forge v 62
Mods I am using...

![Screenshot (45)](https://user-images.githubusercontent.com/8423696/80554521-54d1a280-8982-11ea-8238-650c36791fce.png)
![Screenshot (46)](https://user-images.githubusercontent.com/8423696/80554523-5602cf80-8982-11ea-84bd-d81e462c7a26.png)
![Screenshot (47)](https://user-images.githubusercontent.com/8423696/80554526-5733fc80-8982-11ea-95a0-4e1561e0cbae.png)
![Screenshot (48)](https://user-images.githubusercontent.com/8423696/80554531-57cc9300-8982-11ea-84c7-9d840f464576.png)
![Screenshot (49)](https://user-images.githubusercontent.com/8423696/80554532-58fdc000-8982-11ea-804e-95ee4e9ac9b7.png)
![Screenshot (50)](https://user-images.githubusercontent.com/8423696/80554534-5a2eed00-8982-11ea-837e-7fc6bd5cf12c.png)
![Screenshot (51)](https://user-images.githubusercontent.com/8423696/80554535-5ac78380-8982-11ea-835b-8025c0ea1d92.png)

**Comment by Tfarcenim** [comment]
missing Extra Tags

**Comment by RepoDraghon** [comment]
what tags are missing or are you just telling me you fixed it in the next version?

**Comment by Tfarcenim** [comment]
https://www.curseforge.com/minecraft/mc-mods/extra-tags
