### ISSUE TITLE
JEI Cheat Mode - Items Being Deleted

### ISSUE THREAD

**Issue by nephatrine** [Tfarcenim/crafting-station#57]
Using JEI in cheat mode, the leftmost slots of adjacent storage are inevitably in the "Click To Delete" area and so I've accidentally managed to delete items on numerous occasions while trying to put them back in an attached chest. Is there a way to override JEI so that the click to delete behavior isn't active when the Crafting Station is open?

**Comment by Tfarcenim** [comment]
this has been fixed in recent versions, open a new issue if it still persists in 1.16.5
