### ISSUE TITLE
[suggestion] Option to disable extended inventory completely

### ISSUE THREAD

**Issue by Basedgod199** [Tfarcenim/crafting-station#58]
pretty self-explanatory, just a way to completely remove the crafting stations ability to grab inventories next to it. Or at the very least, a functional blacklist, as i've tried multiple times to blacklist thermal foundation blocks with no success. on top of that even the inventories that will respect the blacklist don't retain their blacklist when Minecraft is restarted

**Comment by Tfarcenim** [comment]
Done
