### ISSUE TITLE
Compat with Storage Overhaul

### ISSUE THREAD

**Issue by WenXin20** [Tfarcenim/crafting-station#59]
`Minecraft v1.15.2`
`Forge v31.2.19`
`Crafting Station v3.1.0`
[`Storage Overhaul v1.0.4`](https://www.curseforge.com/minecraft/mc-mods/storage-overhaul) 

Currently, if I make a double chest using any chest from this mod, the Crafting Station doesn't recognizeit, so the inventory shown is only that of a single chest without a scrollbar.
Is this possible to add support for?

**Comment by Tfarcenim** [comment]
This is the same issue as #54, again, is there a fix without hardcoding?

**Comment by Tfarcenim** [comment]
see #54
