### ISSUE TITLE
Trim Long Inventory Names

### ISSUE THREAD

**Issue by WenXin20** [Tfarcenim/crafting-station#60]
`Minecraft v1.15.2`
[`Storage Overhaul v1.0.4`](https://www.curseforge.com/minecraft/mc-mods/storage-overhaul)

Some chests have long inventory names, which overlaps other text. Is it possible to trim it?

![2020-06-17_18 50 33](https://user-images.githubusercontent.com/12000593/84963029-e7aed380-b0cd-11ea-996f-86a9a2b4451f.png)

**Comment by Tfarcenim** [comment]
1.18 versions do this now.
