### ISSUE TITLE
1.16.1 crafting station v4.0.0 causes crashes on start (custom mod pack)

### ISSUE THREAD

**Issue by PurpleHel** [Tfarcenim/crafting-station#62]
Dunno why, but when I disable it, the crashes stop.
crash log https://pastebin.com/0zk9iezN
all the mods I'm using https://pastebin.com/nzQidzmy

**Comment by Tfarcenim** [comment]
You're missing https://www.curseforge.com/minecraft/mc-mods/extra-tags, updated dependency list to enforce this

**Comment by PurpleHel** [comment]
D'oh! Now I feel dumb. Glad it's such an easy fix tho!
