### ISSUE TITLE
[1.16.3][Forge34.1.22] java.lang.IllegalStateException: Missing required tags: minecraft:block_entity_type:craftingstation:blacklisted

### ISSUE THREAD

**Issue by raziel23x** [Tfarcenim/crafting-station#67]
Latest Log of the issue
https://gist.github.com/raziel23x/b0e9eb960c7bfe308a89c524948a0202
when trying to create a world or load into a world with the latest 34.1.22 forge the game will freak out about datapacks because of java.lang.IllegalStateException: Missing required tags: minecraft:block_entity_type:craftingstation:blacklisted
![image](https://user-images.githubusercontent.com/441966/96278283-511ef000-0fa3-11eb-872c-5fb5f65d3d18.png)

**Comment by FullMetalMaster** [comment]
yeah same

**Comment by bblewitt** [comment]
Same here but on forge 34.1.23 but it was fine on 34.1.05.

**Comment by raziel23x** [comment]
Forge 34.1.21 and below the mod works just fine but the 34.1.22 update introduced tags and fixed many mapping issues which in turn breaks the mod due to hacky code that was used to call the entity type which is conflicting with forge as they are using different names

**Comment by ProsperCraft** [comment]
Thank you.
