### ISSUE TITLE
[1.12.2] Tile Entity blacklist doesn't work sometimes

### ISSUE THREAD

**Issue by aaronhowser1** [Tfarcenim/crafting-station#69]
```
    # Blacklisted tile entities should be specified in modid:name format
    S:"Tile entity blacklist" <
        yabba:item_barrel
     >
```

This works completely fine.

```
    # Blacklisted tile entities should be specified in modid:name format
    S:"Tile entity blacklist" <
        yabba:item_barrel
        compactdrawers:compact_drawer_2by1
        compactdrawers:compact_drawer_2by1_half
        compactdrawers:compact_drawer_half
        framedcompactdrawers:framed_compact_drawer
        framedcompactdrawers:framed_compact_drawer_controller
        storagedrawers:basicdrawers
        storagedrawers:compdrawers
        storagedrawers:controller
        storagedrawers:customdrawers
     >
```

Now, all of these crash (#68), including the YABBA one which worked when it was alone.

```
    # Blacklisted tile entities should be specified in modid:name format
    S:"Tile entity blacklist" <
        storagedrawers:basicdrawers
     >
```
This does not work, possibly because the block itself also has metadata (`storagedrawers:basicdrawers 0`, `1`, `2`, `3`, etc). How would I configure this?

This is using 1.12, and `craftingstation-0.1.7c`.

Reported from FTBTeam/FTB-University/issues/42

**Comment by Tfarcenim** [comment]
Nope, it has nothing to do with the block or metadata, the mod checks the block entity name directly.  The right names for storage drawers are ```storagedrawers:basicdrawers.1
storagedrawers:basicdrawers.2
storagedrawers:basicdrawers.4
storagedrawers:basicdrawers.2
storagedrawers:basicdrawers.4```, I added a debug print when opening the crafting station to help with this
