### ISSUE TITLE
[1.12.2] GUI not aligned properly

### ISSUE THREAD

**Issue by Dmitchell94** [Tfarcenim/crafting-station#71]
Running
- Crafting Station 0.1.8
- Forge 2854

The inventory spaces within the crafting station are not aligned to the graphic causing the input and output to overlap. Even after disabling crafting tweaks I am still seeing this issue
![INVENTORY LINEUP](https://user-images.githubusercontent.com/1408174/98034626-5377ab80-1de5-11eb-9aad-780b9f342ef3.png)
![INVENTORY LINEUP2](https://user-images.githubusercontent.com/1408174/98034628-54104200-1de5-11eb-95b2-3ee1b249ac0a.png)

**Comment by twothe** [comment]
Can confirm.

![image](https://user-images.githubusercontent.com/1131621/98045672-25b45600-1e29-11eb-9fa1-8bcf7ed3f483.png)

**Comment by Elrol** [comment]
Ditto
![image](https://user-images.githubusercontent.com/12816881/98055520-42d62e00-1e03-11eb-98ef-6bb1365a3bdd.png)
