### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by MathiewMay2** [Tfarcenim/crafting-station#77]
I found a dupe glitch with this mod i would not suggest using it, i will post a video show how it work tomorrow but basically what you need to do is put a crafting station next to a chest (preferably double) and put in the materials for a 3x3 craft except for 1 slot then have a friend shift click the last required item from the chest into the crafting station and spam it, once hes spamming that you spam to take the output, and it will dupe all the items of the crafting recipe next just spam the X button (red square) and it will keep filling the chest and your inventory with those items.

Running version 4.111

**Comment by Tfarcenim** [comment]
I tried, couldn't get it to work.

**Comment by Tfarcenim** [comment]
closing as unreproducible
