### ISSUE TITLE
crafting station vanishes on break and will not pull from connected container for crafting minecraft 1.14.4

### ISSUE THREAD

**Issue by raziel23x** [Tfarcenim/crafting-station#8]
**Issue description:**
when breaking the station it disappears and will not pull items from the connected chest when crafting from the JEI
**If crashed, link to crash report (use a site such as pastebin):**
N/A
**Versions:**
* Minecraft: 1.14.4
* Forge: 1.14.4-28.0.24
* Mantle: Has not been ported to Minecraft: 1.14.4 yet
* Tinkers Construct: Has not been ported to Minecraft: 1.14.4 yet

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**  No

**Comment by Tfarcenim** [comment]
fixed in 2.0.1, this mod is meant to be used standalone, but it could be used with tic if one really felt like it
