### ISSUE TITLE
[1.16.5] Unsure how to blacklist containers

### ISSUE THREAD

**Issue by faeldray** [Tfarcenim/crafting-station#80]
From what I've been able to piece together from various sources is that in order to accomplish blacklisting a container from the crafting station, I need to:

- have the Extra Tags mod also installed
- create a data pack to add the "craftingstation:blacklisted" tag to the tile entity

So I created a `blacklisted.json` file inside a datapack in the directory `data\craftingstation\tags\block_entity_types`. And this is the code inside:

```
{
    "replace":false,
    "values": [
        "druidcraft:crate",
        "enderchests:ender_chest.tile"
    ]
}
```

But the containers are still showing up on the crafting station's tabs. I'm new at creating datapacks so it's possible I got something wrong. Any help would be greatly appreciated.

**Comment by Tfarcenim** [comment]
That's been changed, Extra Tags is no longer needed and it's now `tile_entity_types` due to a Forge change.

**Comment by faeldray** [comment]
That worked, thanks!
