### ISSUE TITLE
1.18.x port plans

### ISSUE THREAD

**Issue by CKY-** [Tfarcenim/crafting-station#82]
is there any plans to port to 1.18,x

**Comment by Tfarcenim** [comment]
When forge is stable

**Comment by Darkmift** [comment]
Sure miss this on 1.18 and above

**Comment by Tfarcenim** [comment]
I'm currently making a few higher priority mods, but it will be ready in November.

**Comment by CKY-** [comment]
Thank you for the update I for one love this mod

**Comment by Tfarcenim** [comment]
And done

**Comment by Darkmift** [comment]
Awesome!
