### ISSUE TITLE
buttons from polymorph&crafting tweaks not displaying properly/at all 1.19.2

### ISSUE THREAD

**Issue by PurpleHel** [Tfarcenim/crafting-station#85]
* Forge 43.1.57
* craftingstation-1.19.2-6
* Polymorph: Tested with both polymorph-forge-0.46.0+1.19.2 and polymorph-forge-0.46.1+1.19.2
* crafting tweaks 15.1.0
As you can see, crafting tweaks is only showing one button instead of all 3, and the poly morph button isn't rendering at all. I reported this to polymorph, but I think it's probably an issue with crafting station cos the buttons are working on every other crafting table/work station I've got installed. https://imgur.com/a/PaJKbAS

**Comment by Tfarcenim** [comment]
I have no idea how to do compat.

**Comment by adamico** [comment]
@Tfarcenim I'd like to help solving this issue and maybe adding a compat api for any crafting gui. Is it ok if I send a PR?

adamico/mechanical-mastery-plus#78

**Comment by Tfarcenim** [comment]
Fixed in 1.20.1
