### ISSUE TITLE
[1.19.2] Interaction with create 0.5 multiblock item vaults

### ISSUE THREAD

**Issue by zaftnotameni** [Tfarcenim/crafting-station#87]
Noticed that placing the crafting station next to a multiblock vault, it "erases" the player inventory, at least visually.

Before placing the crafting station

![2023-01-06_14 20 54](https://user-images.githubusercontent.com/122100803/211022015-a7f23038-95d6-457a-af55-4d097bcf33be.png)

Crafting station open (see player inventory blank, but should have 2 picks)

![2023-01-06_14 21 06](https://user-images.githubusercontent.com/122100803/211022051-46f1bbb1-2b72-4c92-800f-209af6930f82.png)

After closing the crafting station, see UI still shows the inventory as empty

![2023-01-06_14 21 10](https://user-images.githubusercontent.com/122100803/211022104-4aaba8f9-39ae-43f3-b618-ae959250581c.png)

If i just click or shift click where the items where, they show up again, so they just become invisible in the player inventory.

Have not tested this on single player, but it is happening consistently on a server, no matter what I have in my inventory.

**Comment by ClaudiusMinimus** [comment]
[zaftnotameni](https://github.com/zaftnotameni), thank you for posting this. 

This is part of my pack, [Create on a Potato PC: Sky Edition](https://www.curseforge.com/minecraft/modpacks/create-on-a-potato-pc-sky) and the multiblock vault in question is from the mod, [Create](https://www.curseforge.com/minecraft/mc-mods/create).

To provide a bit more information:
Minecraft version: 1.19.2
Forge: 43.2.0
Crafting Station: 1.19.2-6
Create: [1.19.2-0.5.0.g](https://www.curseforge.com/minecraft/mc-mods/create/files/4174330)

zaftnotameni, Please upload your latest.log and debug.log files as well - may help the developer solve this issue.

Thank you,
CM

**Comment by zaftnotameni** [comment]
[debug-during-problem.log](https://github.com/Tfarcenim/crafting-station/files/10360582/debug-during-problem.log)
[latest-during-problem.log](https://github.com/Tfarcenim/crafting-station/files/10360583/latest-during-problem.log)

good call on the logs, it seems like inventory sorter is probably partially to blame here

**Comment by Tfarcenim** [comment]
Seems like there is a desync between what the server is saying the slot count is and what the client is saying it has, I'm going to shove it into the default blockentity blacklist unless someone has a better fix that isn't hardcoding like I have to do with the vanilla double chest.

**Comment by Tfarcenim** [comment]
After looking at what the item vault does, I've decided to go ahead and blacklist it since it's a multiblock and the crafting station wasn't designed to be used with them.

**Comment by ClaudiusMinimus** [comment]
Thank you!

**Comment by ClaudiusMinimus** [comment]
I just updated and tested. It seems the crafting station still connects to the vault, but without the visual glitch. I can pull items manually from it, but the crafting station does not automatically pull for crafting. Is this what you intended?
![image](https://user-images.githubusercontent.com/17887664/212801756-c043412c-b936-4044-a0e6-7d59411753e4.png)
