### ISSUE TITLE
[1.19.3] Crafting station doesn't have the JEI + button to send items to the crafting grid.

### ISSUE THREAD

**Issue by ProsperCraft** [Tfarcenim/crafting-station#88]
looks like this-
![image](https://user-images.githubusercontent.com/4427684/221453075-1967aaca-168b-4512-81e4-56c3ec177003.png)

Should look like this-
![image](https://user-images.githubusercontent.com/4427684/221453094-cd5f7658-da8e-41b6-a41b-9956aeeefbe7.png)

**Comment by Tfarcenim** [comment]
The mod has switched from JEI to REI permanently.
