### ISSUE TITLE
[1.19.2-6.0.1] Odd rendering crash

### ISSUE THREAD

**Issue by kreezxil** [Tfarcenim/crafting-station#90]
I was hitting "esc" to leave the station. https://gist.github.com/kreezxil/3f53f1d5c92b81767f719444e83fe9f7

**Comment by ClaudiusMinimus** [comment]
Ditto, I have a player who is getting the same crash in my pack, [Create on a Potato PC: Ultimate](https://legacy.curseforge.com/minecraft/modpacks/create-on-a-potato/files/4571077), which also has Crafting Station 1.19.2-6.0.1.

In the player's words:
> i close the quest with spamming esc too fast and the game was crash happen all the time

## Crash Report
[Formatted](https://crashy.net/6cfc266f-164d-4c5a-a589-9d8495fc8ec2) [Raw](https://crashy.net/6cfc266f-164d-4c5a-a589-9d8495fc8ec2/raw.txt)

**Comment by kreezxil** [comment]
ok it happened again, but this time the players are saying it happens (2 players now) when they are in the crafting station but click on the "quest book" and then go to exit that with esc.

their crash report: https://pastebin.com/5LRuxBpt

**Comment by vedrit** [comment]
To add additional information to @ClaudiusMinimus with Create on a Potato Ultimate, if a player interacts with the crafting station and then opens the FTB quest window, pressing either the 'e' key or 'esc' key will cause the client to crash. Does not require spamming either key.
https://pastebin.com/JsZewawM

**Comment by Tfarcenim** [comment]
Fixed on 6.0.3
