### ISSUE TITLE
Not compatible with JEI

### ISSUE THREAD

**Issue by twothe** [Tfarcenim/crafting-station#92]
When using the Crafting Station with Minecraft 1.20.1 resources from recipes from JEI cannot be automatically put into the crafting slots ([+] button not present).

**Comment by Tfarcenim** [comment]
Use REI

**Comment by twothe** [comment]
That is certainly not going to happen, and no major modpack will follow that advice. With that not working your mod will simply not be included in any major modpack.

Maybe you want to reconsider.

**Comment by Leclowndu93150** [comment]
Lmao wtf is that argument

**Comment by choekstr** [comment]
Wait, this is effectively a status of: "closed, won't fix, don't use that mod and instead use a different mod of my choosing"?  

LMAO indeed, that is pretty much going to be a crapshoot if a modpack and associated dev decides to use REI or JEI.  

I would request a reconsider with as much compatibility as possible given a large portion of the popular modpacks rely on JEI over REI

**Comment by Leclowndu93150** [comment]
lmao

**Comment by Tfarcenim** [comment]
I use REI because it's easier to code for, has more features than JEI, and is more practical for use in multiloader projects (fabric JEI is basically a meme).  If you don't like it, then make your own mod.

**Comment by Tfarcenim** [comment]
> That is certainly not going to happen, and no major modpack will follow that advice. With that not working your mod will simply not be included in any major modpack.

> Maybe you want to reconsider.

If you aren't the one paying money, you have no right to tell others what to do

**Comment by Tfarcenim** [comment]
For the record, from 1.19.3 forward, this mod uses REI integration and ONLY REI integration, JEI support being missing isn't a bug, it's intended for the reasons I listed above.

**Comment by twothe** [comment]
Well then this mod is officially dead. Thank you for the time it worked.

**Comment by AmmoniumX** [comment]
@Tfarcenim 
I'm sad that JEI support is no longer going to be supported now since many modpacks are still made with it, but you are the mod maintainer, so I respect your decision.
That being said, I would like to ask if you would be opposed to a pull request adding back JEI support?

**Comment by Fureniku** [comment]
> I use REI because it's easier to code for, has more features than JEI, and is more practical for use in multiloader projects (fabric JEI is basically a meme). If you don't like it, then make your own mod.

Under MIT we can technically just fork this, add it, and release it.

I've done the first two steps, so figured I'd just ask if you want me to PR it in, and if not I'll just put it on CF as a JEI version. But it seems a lot of people want it, and its literally ~20 lines of code, so it'd be nice to just get it in the "official" release.

**Comment by Leclowndu93150** [comment]
i can release it for you if you want lmao

**Comment by AmmoniumX** [comment]
> > I use REI because it's easier to code for, has more features than JEI, and is more practical for use in multiloader projects (fabric JEI is basically a meme). If you don't like it, then make your own mod.
> 
> Under MIT we can technically just fork this, add it, and release it.
> 
> I've done the first two steps, so figured I'd just ask if you want me to PR it in, and if not I'll just put it on CF as a JEI version. But it seems a lot of people want it, and its literally ~20 lines of code, so it'd be nice to just get it in the "official" release.

You got ahead of me, congrats ;).
I asked if they would be open to a PR on my earlier reply, but if they weren't then the solution needs to be forking. Given how they haven't replied to my question since, I guess the answer is "no".
Good luck with your fork, you have my support

**Comment by Fureniku** [comment]
> > > I use REI because it's easier to code for, has more features than JEI, and is more practical for use in multiloader projects (fabric JEI is basically a meme). If you don't like it, then make your own mod.
> > 
> > 
> > Under MIT we can technically just fork this, add it, and release it.
> > I've done the first two steps, so figured I'd just ask if you want me to PR it in, and if not I'll just put it on CF as a JEI version. But it seems a lot of people want it, and its literally ~20 lines of code, so it'd be nice to just get it in the "official" release.
> 
> You got ahead of me, congrats ;). I asked if they would be open to a PR on my earlier reply, but if they weren't then the solution needs to be forking. Given how they haven't replied to my question since, I guess the answer is "no". Good luck with your fork, you have my support

I'm already done. It's an incredibly simple addition, and took me just over an hour between thinking "I should do that" and having it on my server. It's also an entirely client based change, so you wont even need the server to update to the new version.

CF takes a day or two to approve a project at the best of times and I imagine its longer due to the holidays, so I'll give Tfarcenim until its approved to decide

**Comment by choekstr** [comment]
@Tfarcenim It would be much cleaner if the PR could be merged into your version so it helps the community by having less versions.  Is this something you would be willing to accept to strengthen this already great mod?

Thanks for your consideration.

**Comment by Fureniku** [comment]
Forgot to come back and say but due to lack of response, the patched version was released. I've also fixed the item rendering, fixed the rotation issue (#70), and added Polymorph support (#85):
https://www.curseforge.com/minecraft/mc-mods/crafting-station-jei-edition
