### ISSUE TITLE
[1.19.2] Blacklist doesnt appear to be working

### ISSUE THREAD

**Issue by Saereth** [Tfarcenim/crafting-station#96]
Using the included blacklisting datapack file as reference I tried toggling required to true or false on the create item vault and it was able to still show and interact with the crafting station. I dont see a tag being applied to the block in f3 either. What is the exact tag that I should be applying to the blocks?

**Comment by Tfarcenim** [comment]
> I dont see a tag being applied to the block in f3 either.

That's your issue, use blockentity tags, not block tags
